// Generates src/internal/icon-data.ts: the inline SVG icons of the library
// (same icons as React's src/internal/icons.tsx, read from the Web
// Components' generated copy) as plain data rendered by the internal
// <svg mnIcon> component, without innerHTML (no sanitizer bypass, SSR-safe).
//   node scripts/icons.mjs          -> writes the file
//   node scripts/icons.mjs --check  -> exits 1 when it is stale
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const SOURCE = join(here, "../../web-components/src/internal/icons.ts");
const OUTPUT = join(here, "../src/internal/icon-data.ts");

export async function iconDataSource() {
  const source = readFileSync(SOURCE, "utf8");
  const icons = [];
  for (const [, name, kind, body] of source.matchAll(
    /export const Icon(\w+) = (stroke|fill)\(\s*svg`([^`]*)`,?\s*\);/g,
  )) {
    const nodes = [];
    for (const [, tag, attrs] of body.matchAll(/<(\w+)([^>]*?)\s*\/>/g)) {
      const attributes = Object.fromEntries(
        Array.from(attrs.matchAll(/([\w-]+)="([^"]*)"/g), (m) => [m[1], m[2]]),
      );
      nodes.push([tag, attributes]);
    }
    icons.push([name, kind, nodes]);
  }
  if (icons.length < 30) throw new Error(`Parsed only ${icons.length} icons`);
  const tags = new Set(icons.flatMap(([, , nodes]) => nodes.map((n) => n[0])));
  for (const tag of tags) {
    if (!["path", "circle", "rect"].includes(tag))
      throw new Error(`Unsupported SVG element <${tag}> in the icons`);
  }
  const lines = icons.map(
    ([name, kind, nodes]) =>
      `  ${name}: { fill: ${kind === "fill"}, nodes: ${JSON.stringify(nodes)} },`,
  );
  const code = `// Generated by packages/angular/scripts/icons.mjs from the library icons
// (React src/internal/icons.tsx, stroke geometry largely from Lucide, ISC
// license: see React): do not edit.

/** An SVG child element: tag name and attributes */
export type IconNode = readonly [
  "path" | "circle" | "rect",
  Readonly<Record<string, string>>,
];

export interface IconData {
  /** Solid icon (filled, even-odd cut-outs) instead of an outline */
  readonly fill: boolean;
  readonly nodes: readonly IconNode[];
}

export const ICONS = {
${lines.join("\n")}
} as const satisfies Record<string, IconData>;

/** Name of a library icon */
export type IconName = keyof typeof ICONS;
`;
  const prettier = await import("prettier");
  const options = (await prettier.resolveConfig(OUTPUT)) ?? {};
  return prettier.format(code, { ...options, filepath: OUTPUT });
}

const isMain =
  process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (isMain) {
  const next = await iconDataSource();
  if (process.argv.includes("--check")) {
    if (readFileSync(OUTPUT, "utf8") !== next) {
      console.error(
        "src/internal/icon-data.ts is out of date: run `node scripts/icons.mjs`",
      );
      process.exit(1);
    }
  } else {
    writeFileSync(OUTPUT, next);
  }
}
