// Class maps of the shared stylesheet contract (the React SCSS modules).
//
// The Angular components use the exact classes of `minerva-design/style.css`
// (compiled from packages/react/src/components/**/*.module.scss). Their names
// are CSS-module scoped in the build (`_customButton_2ei12_1`) and unscoped
// in tests (`customButton`, like the React / Web Components tests).
//
// - `src/internal/styles.ts` (committed): one map per SCSS module with the
//   unscoped names (key = value), regenerated by `pnpm --filter
//   @minerva/angular styles` (`--check`: exit 1 when stale; a unit test runs
//   the check too).
// - `scopedStylesSource()`: the same module with the scoped names of the
//   React build (dist/react/**/*.module.scss.js), written into the staged
//   sources by scripts/build.mjs before ng-packagr compiles them.
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { basename, dirname, join, relative } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import * as sass from "sass";

const here = dirname(fileURLToPath(import.meta.url));
export const ANGULAR_DIR = join(here, "..");
const REACT_SRC = join(ANGULAR_DIR, "../react/src");
export const STYLES_FILE = join(ANGULAR_DIR, "src/internal/styles.ts");

/** SCSS modules of the React components (sorted, relative to react/src) */
export function scssModules() {
  // (no fs.globSync: the package build also runs on Node 20)
  const walk = (dir) =>
    readdirSync(join(REACT_SRC, dir), { withFileTypes: true }).flatMap((e) =>
      e.isDirectory() ? walk(`${dir}/${e.name}`) : [`${dir}/${e.name}`],
    );
  return walk("components")
    .filter((file) => file.endsWith(".module.scss"))
    .sort();
}

/** `button.module.scss` -> `buttonStyles` */
export const exportName = (file) => `${basename(file, ".module.scss")}Styles`;

/** Local class (and keyframes) names of a SCSS module, as postcss-modules exports them */
export function classKeys(file) {
  const css = sass
    .compile(join(REACT_SRC, file))
    .css.replace(/\/\*[\s\S]*?\*\//g, "");
  const keys = new Set();
  for (const [, selector] of css.matchAll(/([^{}]+)\{/g)) {
    if (/^\s*@/.test(selector)) {
      const keyframes = /@(?:-webkit-)?keyframes\s+([\w-]+)/.exec(selector);
      if (keyframes) keys.add(keyframes[1]);
      continue;
    }
    const cleaned = selector
      .replace(/:global\([^)]*\)/g, "")
      .replace(/url\([^)]*\)/g, "")
      .replace(/"[^"]*"|'[^']*'/g, "");
    for (const [, name] of cleaned.matchAll(/\.(-?[_a-zA-Z][\w-]*)/g))
      keys.add(name);
  }
  return [...keys].sort();
}

const HEADER = `// Generated by packages/angular/scripts/styles.mjs from the React SCSS
// modules (packages/react/src/components/**/*.module.scss): do not edit.
// Unscoped class names (tests, like the React / Web Components tests); the
// package build replaces the values with the scoped names of
// \`minerva-design/style.css\` (scripts/build.mjs).

/** A class map of a SCSS module (class name -> class of the stylesheet) */
export type ClassMap<K extends string> = Readonly<Record<K, string>>;
`;

const quote = (key) =>
  /^[A-Za-z_$][\w$]*$/.test(key) ? key : JSON.stringify(key);

/** The styles module, values from `valueOf(file, key)` */
function render(valueOf) {
  const blocks = scssModules().map((file) => {
    const keys = classKeys(file);
    const type = keys.map((k) => JSON.stringify(k)).join(" | ");
    const entries = keys
      .map((key) => `  ${quote(key)}: ${JSON.stringify(valueOf(file, key))},`)
      .join("\n");
    return `/** ${file} */\nexport const ${exportName(file)}: ClassMap<${type}> = {\n${entries}\n};\n`;
  });
  return `${HEADER}\n${blocks.join("\n")}`;
}

async function format(code) {
  const prettier = await import("prettier");
  const options = (await prettier.resolveConfig(STYLES_FILE)) ?? {};
  return prettier.format(code, { ...options, filepath: STYLES_FILE });
}

/** The committed module: unscoped names */
export const unscopedStylesSource = () => format(render((_, key) => key));

/**
 * The module with the scoped class names of the React build
 * (`<reactDist>/components/<folder>/<file>.module.scss.js`); throws when a
 * class of the SCSS is missing from the build (or the reverse).
 */
export async function scopedStylesSource(reactDist) {
  const maps = new Map();
  for (const file of scssModules()) {
    const built = join(reactDist, `${file}.js`);
    const map = (await import(pathToFileURL(built).href)).default;
    const keys = classKeys(file);
    const builtKeys = Object.keys(map).sort();
    if (keys.join() !== builtKeys.join()) {
      throw new Error(
        `${relative(ANGULAR_DIR, built)}: classes differ from the SCSS (${keys.filter((k) => !(k in map))} / ${builtKeys.filter((k) => !keys.includes(k))})`,
      );
    }
    maps.set(file, map);
  }
  return format(render((file, key) => maps.get(file)[key]));
}

const isMain =
  process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (isMain) {
  const next = await unscopedStylesSource();
  if (process.argv.includes("--check")) {
    if (readFileSync(STYLES_FILE, "utf8") !== next) {
      console.error(
        "src/internal/styles.ts is out of date: run `pnpm --filter @minerva/angular styles`",
      );
      process.exit(1);
    }
  } else {
    writeFileSync(STYLES_FILE, next);
    console.log(`Wrote ${relative(process.cwd(), STYLES_FILE)}`);
  }
}
