import type {
  InteractiveIconState,
  InteractiveIconType,
} from "./interactive-types";

// Active colors are intentional per-icon accents (heart = pink, star = amber,
// ...). Backgrounds are translucent tints and inactive icons use the theme
// text color so the presets read well on light and dark themes.
export const interactiveIconsMap: Record<
  InteractiveIconType,
  InteractiveIconState
> = {
  favorite: {
    label: "Favorite",
    isActive: false,
    activeColor: "#e91e63",
    inactiveColor: "var(--text-secondary-color)",
    activeBgColor: "color-mix(in srgb, #e91e63 14%, transparent)",
    inactiveBgColor: "transparent",
    activeHoverColor: "color-mix(in srgb, #e91e63 22%, transparent)",
    inactiveHoverColor: "rgba(233, 30, 99, 0.12)",
    activeFillColor: "#e91e63",
    inactiveFillColor: "transparent",
    activeTooltip: "Remove from favorites",
    inactiveTooltip: "Add to favorites",
  },
  bookmark: {
    label: "Bookmark",
    isActive: false,
    activeColor: "#ffc107",
    inactiveColor: "var(--text-secondary-color)",
    activeBgColor: "color-mix(in srgb, #ffc107 14%, transparent)",
    inactiveBgColor: "transparent",
    activeHoverColor: "color-mix(in srgb, #ffc107 22%, transparent)",
    inactiveHoverColor: "rgba(255, 193, 7, 0.12)",
    activeFillColor: "#ffc107",
    inactiveFillColor: "transparent",
    activeTooltip: "Remove bookmark",
    inactiveTooltip: "Add bookmark",
  },
  star: {
    label: "Star",
    isActive: false,
    activeColor: "#ff9800",
    inactiveColor: "var(--text-secondary-color)",
    activeBgColor: "color-mix(in srgb, #ff9800 14%, transparent)",
    inactiveBgColor: "transparent",
    activeHoverColor: "color-mix(in srgb, #ff9800 22%, transparent)",
    inactiveHoverColor: "rgba(255, 152, 0, 0.12)",
    activeFillColor: "#ff9800",
    inactiveFillColor: "transparent",
    activeTooltip: "Remove star",
    inactiveTooltip: "Add star",
  },
  like: {
    label: "Like",
    isActive: false,
    activeColor: "#e91e63",
    inactiveColor: "var(--text-secondary-color)",
    activeBgColor: "color-mix(in srgb, #e91e63 14%, transparent)",
    inactiveBgColor: "transparent",
    activeHoverColor: "color-mix(in srgb, #e91e63 22%, transparent)",
    inactiveHoverColor: "rgba(233, 30, 99, 0.12)",
    activeFillColor: "#e91e63",
    inactiveFillColor: "transparent",
    activeTooltip: "Unlike",
    inactiveTooltip: "Like",
  },
  follow: {
    label: "Follow",
    isActive: false,
    activeColor: "#2196f3",
    inactiveColor: "var(--text-secondary-color)",
    activeBgColor: "color-mix(in srgb, #2196f3 14%, transparent)",
    inactiveBgColor: "transparent",
    activeHoverColor: "color-mix(in srgb, #2196f3 22%, transparent)",
    inactiveHoverColor: "rgba(33, 150, 243, 0.12)",
    activeFillColor: "#2196f3",
    inactiveFillColor: "transparent",
    activeTooltip: "Unfollow",
    inactiveTooltip: "Follow",
  },
  share: {
    label: "Share",
    isActive: false,
    activeColor: "#4caf50",
    inactiveColor: "var(--text-secondary-color)",
    activeBgColor: "color-mix(in srgb, #4caf50 14%, transparent)",
    inactiveBgColor: "transparent",
    activeHoverColor: "color-mix(in srgb, #4caf50 22%, transparent)",
    inactiveHoverColor: "rgba(76, 175, 80, 0.12)",
    activeFillColor: "#4caf50",
    inactiveFillColor: "transparent",
    activeTooltip: "Shared",
    inactiveTooltip: "Share",
  },
  notification: {
    label: "Notifications",
    isActive: false,
    activeColor: "#9c27b0",
    inactiveColor: "var(--text-secondary-color)",
    activeBgColor: "color-mix(in srgb, #9c27b0 14%, transparent)",
    inactiveBgColor: "transparent",
    activeHoverColor: "color-mix(in srgb, #9c27b0 22%, transparent)",
    inactiveHoverColor: "rgba(156, 39, 176, 0.12)",
    activeFillColor: "#9c27b0",
    inactiveFillColor: "transparent",
    activeTooltip: "Notifications on",
    inactiveTooltip: "Turn on notifications",
  },
  pin: {
    label: "Pin",
    isActive: false,
    activeColor: "#f44336",
    inactiveColor: "var(--text-secondary-color)",
    activeBgColor: "color-mix(in srgb, #f44336 14%, transparent)",
    inactiveBgColor: "transparent",
    activeHoverColor: "color-mix(in srgb, #f44336 22%, transparent)",
    inactiveHoverColor: "rgba(244, 67, 54, 0.12)",
    activeFillColor: "#f44336",
    inactiveFillColor: "transparent",
    activeTooltip: "Unpin",
    inactiveTooltip: "Pin",
  },
  archive: {
    label: "Archive",
    isActive: false,
    activeColor: "#795548",
    inactiveColor: "var(--text-secondary-color)",
    activeBgColor: "color-mix(in srgb, #795548 14%, transparent)",
    inactiveBgColor: "transparent",
    activeHoverColor: "color-mix(in srgb, #795548 22%, transparent)",
    inactiveHoverColor: "rgba(121, 85, 72, 0.12)",
    activeFillColor: "#795548",
    inactiveFillColor: "transparent",
    activeTooltip: "Unarchive",
    inactiveTooltip: "Archive",
  },
  lock: {
    label: "Lock",
    isActive: false,
    activeColor: "#607d8b",
    inactiveColor: "var(--text-secondary-color)",
    activeBgColor: "color-mix(in srgb, #607d8b 14%, transparent)",
    inactiveBgColor: "transparent",
    activeHoverColor: "color-mix(in srgb, #607d8b 22%, transparent)",
    inactiveHoverColor: "rgba(96, 125, 139, 0.12)",
    activeFillColor: "#607d8b",
    inactiveFillColor: "transparent",
    activeTooltip: "Unlock",
    inactiveTooltip: "Lock",
  },
  download: {
    label: "Download",
    isActive: false,
    activeColor: "#009688",
    inactiveColor: "var(--text-secondary-color)",
    activeBgColor: "color-mix(in srgb, #009688 14%, transparent)",
    inactiveBgColor: "transparent",
    activeHoverColor: "color-mix(in srgb, #009688 22%, transparent)",
    inactiveHoverColor: "rgba(0, 150, 136, 0.12)",
    activeFillColor: "#009688",
    inactiveFillColor: "transparent",
    activeTooltip: "Downloaded",
    inactiveTooltip: "Download",
  },
  visibility: {
    label: "Visibility",
    isActive: false,
    activeColor: "#3f51b5",
    inactiveColor: "var(--text-secondary-color)",
    activeBgColor: "color-mix(in srgb, #3f51b5 14%, transparent)",
    inactiveBgColor: "transparent",
    activeHoverColor: "color-mix(in srgb, #3f51b5 22%, transparent)",
    inactiveHoverColor: "rgba(63, 81, 181, 0.12)",
    activeFillColor: "#3f51b5",
    inactiveFillColor: "transparent",
    activeTooltip: "Hide",
    inactiveTooltip: "Show",
  },
  clock: {
    label: "Reminder",
    isActive: false,
    activeColor: "#673ab7",
    inactiveColor: "var(--text-secondary-color)",
    activeBgColor: "color-mix(in srgb, #673ab7 14%, transparent)",
    inactiveBgColor: "transparent",
    activeHoverColor: "color-mix(in srgb, #673ab7 22%, transparent)",
    inactiveHoverColor: "rgba(103, 58, 183, 0.12)",
    activeFillColor: "#673ab7",
    inactiveFillColor: "transparent",
    activeTooltip: "Remove from history",
    inactiveTooltip: "Add to history",
  },
  rate: {
    label: "Rate",
    isActive: false,
    activeColor: "#ffd700",
    inactiveColor: "var(--text-secondary-color)",
    activeBgColor: "color-mix(in srgb, #ffd700 14%, transparent)",
    inactiveBgColor: "transparent",
    activeHoverColor: "color-mix(in srgb, #ffd700 22%, transparent)",
    inactiveHoverColor: "rgba(255, 215, 0, 0.12)",
    activeFillColor: "#ffd700",
    inactiveFillColor: "transparent",
    activeTooltip: "Rated",
    inactiveTooltip: "Rate",
  },
  thumbDown: {
    label: "Dislike",
    isActive: false,
    activeColor: "#f44336",
    inactiveColor: "var(--text-secondary-color)",
    activeBgColor: "color-mix(in srgb, #f44336 14%, transparent)",
    inactiveBgColor: "transparent",
    activeHoverColor: "color-mix(in srgb, #f44336 22%, transparent)",
    inactiveHoverColor: "rgba(244, 67, 54, 0.12)",
    activeFillColor: "#f44336",
    inactiveFillColor: "transparent",
    activeTooltip: "Remove dislike",
    inactiveTooltip: "Dislike",
  },
  flag: {
    label: "Flag",
    isActive: false,
    activeColor: "#ff5722",
    inactiveColor: "var(--text-secondary-color)",
    activeBgColor: "color-mix(in srgb, #ff5722 14%, transparent)",
    inactiveBgColor: "transparent",
    activeHoverColor: "color-mix(in srgb, #ff5722 22%, transparent)",
    inactiveHoverColor: "rgba(255, 87, 34, 0.12)",
    activeFillColor: "#ff5722",
    inactiveFillColor: "transparent",
    activeTooltip: "Remove flag",
    inactiveTooltip: "Flag",
  },
  close: {
    label: "Close",
    isActive: false,
    activeColor: "#757575",
    inactiveColor: "var(--text-secondary-color)",
    activeBgColor: "color-mix(in srgb, #757575 14%, transparent)",
    inactiveBgColor: "transparent",
    activeHoverColor: "color-mix(in srgb, #757575 22%, transparent)",
    inactiveHoverColor: "rgba(117, 117, 117, 0.12)",
    activeFillColor: "#757575",
    inactiveFillColor: "transparent",
    activeTooltip: "Closed",
    inactiveTooltip: "Close",
  },
};
