// Virtual modules generated by scripts/build-plugins.mjs

declare module "virtual:docs-meta/*" {
  /** `{ [page]: { title, description } }` of one language */
  const meta: Record<string, Record<string, unknown>>;
  export default meta;
}
