// Converts the shared internal icon set into Vue functional components
// (src/internal/icons.ts), so the Vue renderer draws the same icons as React
// and the web components. Source: the web components' generated icons.ts
// (itself generated from the React icons.tsx).
//   node scripts/generate-icons.mjs          (write)
//   node scripts/generate-icons.mjs --check  (exit 1 when stale)
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { format, resolveConfig } from "prettier";

const SOURCE = fileURLToPath(
  new URL("../../web-components/src/internal/icons.ts", import.meta.url),
);
const OUTPUT = fileURLToPath(
  new URL("../src/internal/icons.ts", import.meta.url),
);

export async function generateIcons() {
  const text = readFileSync(SOURCE, "utf8");
  const icons = [
    ...text.matchAll(
      /export const (Icon\w+) = (stroke|fill)\(\s*svg`([^`]*)`,?\s*\);/g,
    ),
  ].map(([, name, kind, body]) => ({ name, kind, body }));
  if (icons.length === 0) throw new Error("no icons found");
  const lines = [
    "// Generated by scripts/generate-icons.mjs from the shared icon set (React",
    "// src/internal/icons.tsx, via the web components): do not edit. Stroke",
    "// geometry largely from Lucide (ISC license: see the React icons).",
    'import { h, type FunctionalComponent, type SVGAttributes } from "vue";',
    "",
    "/** Props of an internal icon (every SVG attribute can be overridden). */",
    "export interface IconProps extends /* @vue-ignore */ SVGAttributes {",
    '  /** Width and height; a number is in px. @default "1em" */',
    "  size?: number | string;",
    "}",
    "",
    "const STROKE = {",
    '  fill: "none",',
    '  stroke: "currentColor",',
    '  "stroke-width": 2,',
    '  "stroke-linecap": "round",',
    '  "stroke-linejoin": "round",',
    "};",
    "const FILL = {",
    '  fill: "currentColor",',
    '  "fill-rule": "evenodd",',
    '  "clip-rule": "evenodd",',
    '  stroke: "none",',
    "};",
    "",
    "/** Decorative 24x24 icon, sized in `em`, drawn with `currentColor`. */",
    "const icon = (",
    "  name: string,",
    "  paint: Record<string, unknown>,",
    "  body: string,",
    "): FunctionalComponent<IconProps> => {",
    '  const component: FunctionalComponent<IconProps> = ({ size = "1em" }, { attrs }) =>',
    '    h("svg", {',
    '      xmlns: "http://www.w3.org/2000/svg",',
    '      viewBox: "0 0 24 24",',
    "      width: size,",
    "      height: size,",
    "      ...paint,",
    '      "aria-hidden": "true",',
    '      focusable: "false",',
    "      ...attrs,",
    "      innerHTML: body,",
    "    });",
    "  component.displayName = name;",
    '  component.props = ["size"];',
    "  return component;",
    "};",
    "",
  ];
  for (const { name, kind, body } of icons) {
    const paint = kind === "stroke" ? "STROKE" : "FILL";
    lines.push(
      `export const ${name} = /* @__PURE__ */ icon("${name}", ${paint}, ${JSON.stringify(body)});`,
    );
  }
  const options = (await resolveConfig(OUTPUT)) ?? {};
  return format(`${lines.join("\n")}\n`, { ...options, filepath: OUTPUT });
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const next = await generateIcons();
  if (process.argv.includes("--check")) {
    if (!existsSync(OUTPUT) || readFileSync(OUTPUT, "utf8") !== next) {
      console.error(
        "src/internal/icons.ts is stale: run node scripts/generate-icons.mjs",
      );
      process.exit(1);
    }
  } else {
    writeFileSync(OUTPUT, next);
  }
}
