// Writes src/global.ts: the Volar `GlobalComponents` typings of the
// `app.use(MinervaVue)` plugin (`<MnButton>`...), published as
// `minerva-design/vue/global`. The component names are the PascalCase value
// exports of the renderer (static read of its barrels, like the contracts
// generator); src/plugin.test.ts checks them against the runtime exports.
//   node scripts/generate-global.mjs          (write)
//   node scripts/generate-global.mjs --check  (exit 1 when stale)
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { format, resolveConfig } from "prettier";
import { readVue } from "../../../tools/generate-contracts.mjs";

const OUTPUT = fileURLToPath(new URL("../src/global.ts", import.meta.url));

/** PascalCase value exports that are not components */
export const NOT_COMPONENTS = new Set(["MinervaVue"]);

export function componentNames() {
  return [...readVue()]
    .filter((name) => /^[A-Z][a-z]/.test(name) && !NOT_COMPONENTS.has(name))
    .filter((name) => name !== "MonacoCodeEditor")
    .sort();
}

export async function generateGlobal() {
  const names = componentNames();
  const text = `// Generated by scripts/generate-global.mjs: do not edit.
// Volar typings of the components registered by \`app.use(MinervaVue)\`
// (default prefix "Mn"): add "minerva-design/vue/global" to the "types" of
// tsconfig.json, or \`import type {} from "minerva-design/vue/global"\`.
import type * as Minerva from "./index";

declare module "vue" {
  export interface GlobalComponents {
${names.map((name) => `    Mn${name}: typeof Minerva.${name};`).join("\n")}
  }
}

export {};
`;
  const options = (await resolveConfig(OUTPUT)) ?? {};
  return format(text, { ...options, filepath: OUTPUT });
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const next = await generateGlobal();
  if (process.argv.includes("--check")) {
    if (!existsSync(OUTPUT) || readFileSync(OUTPUT, "utf8") !== next) {
      console.error(
        "src/global.ts is stale: run node scripts/generate-global.mjs",
      );
      process.exit(1);
    }
  } else {
    writeFileSync(OUTPUT, next);
  }
}
