// Proves that @minerva/lib-core/compat covers @novel-isr/ui 0.1.40's whole
// public API: every runtime export (checked here) and every exported type
// (checked by tsc through the `export type` list below) of its three entries
// ".", "./theme-utils" and "./monaco". The name lists were extracted from
// novel-isr-ui's src/index.ts, src/components/theme-utils.ts and src/monaco.ts
// with the TypeScript compiler API.
import { describe, expect, it } from "vitest";
import * as compat from "./index";
import * as compatThemeUtils from "./theme-utils";
import * as compatMonaco from "./monaco";

export type {
  AlertProps,
  AlertStatus,
  AlertVariant,
  AppShellLabels,
  AppShellNavigationState,
  AppShellProps,
  AppShellSidebarMode,
  AutocompleteOption,
  AutocompleteProps,
  AutocompleteSize,
  AvatarGroupProps,
  AvatarProps,
  AvatarShape,
  AvatarSize,
  BadgeColorScheme,
  BadgeProps,
  BadgeVariant,
  BoxProps,
  ButtonColorScheme,
  ButtonIntent,
  ButtonProps,
  ButtonSize,
  ButtonVariant,
  CardPadding,
  CardProps,
  CardSectionProps,
  CardTitleProps,
  CardVariant,
  CheckboxProps,
  CheckboxSize,
  CodeBlockProps,
  CommandDialogProps,
  CommandItem,
  ConfirmDialogProps,
  ConfirmIntent,
  ConfirmOptions,
  ContextMenuProps,
  DataTableProps,
  DescriptionListItem,
  DescriptionListProps,
  DividerOrientation,
  DividerProps,
  DrawerContentProps,
  DrawerProps,
  DrawerSide,
  DrawerSize,
  EmptyStateProps,
  EmptyStateSize,
  FormControlProps,
  FormFieldProps,
  FormLabelProps,
  FormLayoutProps,
  GridColumns,
  GridItemProps,
  HtmlPreviewProps,
  IconButtonProps,
  InputProps,
  InputSize,
  InputVariant,
  JsonFieldProps,
  KeyValueEditorProps,
  KeyValueEntry,
  KeyValueEntryErrors,
  ListItemProps,
  ListProps,
  LoadingStateProps,
  LoadingStateSize,
  MenuAction,
  MenuEntry,
  MenuProps,
  ModalBodyProps,
  ModalContentProps,
  ModalFooterProps,
  ModalHeaderProps,
  ModalProps,
  ModalSize,
  MonthCalendarEvent,
  MonthCalendarProps,
  NavTreeItem,
  NavTreeItemState,
  NavTreeProps,
  NavTreeSection,
  NumberInputProps,
  NumberInputSize,
  PageHeaderProps,
  PageProps,
  PageSectionProps,
  PageTabProps,
  PageTabsProps,
  PaginationProps,
  PaletteToggleProps,
  PopoverAlign,
  PopoverContentProps,
  PopoverSide,
  ProseProps,
  RadioGroupProps,
  RadioProps,
  RadioSize,
  RatingDimension,
  RatingProps,
  RatingScaleProps,
  RatingSize,
  ResponsiveGridProps,
  SelectItemProps,
  SelectLabelProps,
  SelectProps,
  SelectSeparatorProps,
  SelectSize,
  SkeletonProps,
  SkeletonTextProps,
  SkeletonVariant,
  SpinnerColorScheme,
  SpinnerProps,
  SpinnerSize,
  SplitLayoutProps,
  StackProps,
  StatCardProps,
  StepItem,
  StepsProps,
  SwitchProps,
  SwitchSize,
  TabListProps,
  TabPanelProps,
  TabProps,
  TableCellContentProps,
  TableColumn,
  TableProps,
  TableRootProps,
  TableScrollConfig,
  TableSize,
  TableVariant,
  TabsColorScheme,
  TabsOrientation,
  TabsProps,
  TabsVariant,
  TagColorScheme,
  TagInputProps,
  TagProps,
  TagSize,
  TextLinkProps,
  TextareaProps,
  TextareaResize,
  TextareaSize,
  TextareaVariant,
  ThemeToggleProps,
  ToastOptions,
  ToastPosition,
  ToastProviderProps,
  ToastStatus,
  ToolbarProps,
  TooltipAlign,
  TooltipProps,
  TooltipProviderProps,
  TooltipSide,
  TooltipTone,
  UploadItem,
  UploadProps,
  UseDisclosureProps,
  UseDisclosureReturn,
} from "./index";
export type { Palette, ResolvedTheme, Theme } from "./theme-utils";
export type { MonacoCodeEditorProps } from "./monaco";

/** Runtime exports of @novel-isr/ui "." */
const NOVEL_MAIN_VALUES = [
  "Alert",
  "AppShell",
  "Autocomplete",
  "Avatar",
  "AvatarGroup",
  "Badge",
  "Box",
  "Button",
  "Card",
  "CardBody",
  "CardDescription",
  "CardFooter",
  "CardHeader",
  "CardTitle",
  "Checkbox",
  "CodeBlock",
  "CommandDialog",
  "ConfirmDialog",
  "ConfirmProvider",
  "ContextMenu",
  "DataTable",
  "DescriptionList",
  "Divider",
  "Drawer",
  "DrawerBody",
  "DrawerClose",
  "DrawerContent",
  "DrawerFooter",
  "DrawerHeader",
  "DrawerRoot",
  "DrawerTrigger",
  "EmptyState",
  "FormControl",
  "FormErrorMessage",
  "FormField",
  "FormHelperText",
  "FormLabel",
  "FormLayout",
  "GridItem",
  "HStack",
  "HtmlPreview",
  "IconButton",
  "Input",
  "JsonField",
  "KeyValueEditor",
  "List",
  "ListItem",
  "LoadingState",
  "Menu",
  "Modal",
  "ModalBody",
  "ModalClose",
  "ModalContent",
  "ModalFooter",
  "ModalHeader",
  "ModalRoot",
  "ModalTrigger",
  "MonthCalendar",
  "NavTree",
  "NumberInput",
  "Page",
  "PageHeader",
  "PageSection",
  "PageTab",
  "PageTabs",
  "Pagination",
  "PaletteToggle",
  "Popover",
  "PopoverAnchor",
  "PopoverClose",
  "PopoverContent",
  "PopoverTrigger",
  "Prose",
  "Radio",
  "RadioGroup",
  "Rating",
  "RatingScale",
  "ResponsiveGrid",
  "Select",
  "SelectGroup",
  "SelectItem",
  "SelectLabel",
  "SelectSeparator",
  "Skeleton",
  "SkeletonText",
  "Spinner",
  "SplitLayout",
  "Stack",
  "StatCard",
  "Steps",
  "Switch",
  "Tab",
  "TabList",
  "TabPanel",
  "Table",
  "TableBody",
  "TableCell",
  "TableCellContent",
  "TableHead",
  "TableHeader",
  "TableRoot",
  "TableRow",
  "Tabs",
  "Tag",
  "TagInput",
  "TextLink",
  "Textarea",
  "ThemeProvider",
  "ThemeToggle",
  "ToastProvider",
  "Toolbar",
  "Tooltip",
  "TooltipProvider",
  "Upload",
  "VStack",
  "cn",
  "confirm",
  "matchesShortcut",
  "normalizeShortcuts",
  "toast",
  "useConfirm",
  "useDisclosure",
  "useFormControlContext",
  "useFormControlProps",
  "useTheme",
  "useToast",
];

/** Runtime exports of @novel-isr/ui "./theme-utils" */
const NOVEL_THEME_UTILS_VALUES = [
  "DEFAULT_PALETTE",
  "PALETTES",
  "PALETTE_COOKIE_NAME",
  "THEME_COOKIE_MAX_AGE",
  "THEME_COOKIE_NAME",
  "THEME_INIT_SCRIPT",
  "parsePaletteCookie",
  "parseThemeCookie",
];

/** Runtime exports of @novel-isr/ui "./monaco" */
const NOVEL_MONACO_VALUES = ["MonacoCodeEditor"];

describe("@minerva/lib-core/compat covers the @novel-isr/ui API", () => {
  it.each(NOVEL_MAIN_VALUES)("compat exports %s", (name) => {
    expect((compat as Record<string, unknown>)[name], name).toBeDefined();
  });

  it.each(NOVEL_THEME_UTILS_VALUES)("compat/theme-utils exports %s", (name) => {
    expect(
      (compatThemeUtils as Record<string, unknown>)[name],
      name,
    ).toBeDefined();
  });

  it.each(NOVEL_MONACO_VALUES)("compat/monaco exports %s", (name) => {
    expect((compatMonaco as Record<string, unknown>)[name], name).toBeDefined();
  });

  it("keeps the counts of @novel-isr/ui 0.1.40 (126+8+1 values, 159+3+1 types)", () => {
    expect(NOVEL_MAIN_VALUES).toHaveLength(126);
    expect(NOVEL_THEME_UTILS_VALUES).toHaveLength(8);
    expect(NOVEL_MONACO_VALUES).toHaveLength(1);
  });
});
