import { createSSRApp } from "vue";
import App from "./App.vue";
import Steps from "./minerva/src/Steps.vue";
import ConfirmDialog from "./minerva/src/ConfirmDialog.vue";
import TableCell from "./minerva/src/TableCell.vue";
import Pagination from "./minerva/src/Pagination.vue";
import FormHelperText from "./minerva/src/FormHelperText.vue";
import Cascader from "./minerva/src/Cascader.vue";
import TableHead from "./minerva/src/TableHead.vue";
import Tabs from "./minerva/src/Tabs.vue";
import TableHeader from "./minerva/src/TableHeader.vue";
import PageTabs from "./minerva/src/PageTabs.vue";
import KeyValueEditor from "./minerva/src/KeyValueEditor.vue";
import ModalBody from "./minerva/src/ModalBody.vue";
import PageSection from "./minerva/src/PageSection.vue";
import Prose from "./minerva/src/Prose.vue";
import FormLayout from "./minerva/src/FormLayout.vue";
import Popover from "./minerva/src/Popover.vue";
import Card from "./minerva/src/Card.vue";
import TableRoot from "./minerva/src/TableRoot.vue";
import CardContent from "./minerva/src/CardContent.vue";
import SelectItem from "./minerva/src/SelectItem.vue";
import Radio from "./minerva/src/Radio.vue";
import CommandDialog from "./minerva/src/CommandDialog.vue";
import FormField from "./minerva/src/FormField.vue";
import ModalContent from "./minerva/src/ModalContent.vue";
import PageHeader from "./minerva/src/PageHeader.vue";
import Tab from "./minerva/src/Tab.vue";
import DrawerBody from "./minerva/src/DrawerBody.vue";
import MonthCalendar from "./minerva/src/MonthCalendar.vue";
import Toolbar from "./minerva/src/Toolbar.vue";
import List from "./minerva/src/List.vue";
import VirtualList from "./minerva/src/VirtualList.vue";
import TagInput from "./minerva/src/TagInput.vue";
import ModalTrigger from "./minerva/src/ModalTrigger.vue";
import TableRow from "./minerva/src/TableRow.vue";
import AppShell from "./minerva/src/AppShell.vue";
import DialogSurface from "./minerva/src/DialogSurface.vue";
import ToastProvider from "./minerva/src/ToastProvider.vue";
import CardTitle from "./minerva/src/CardTitle.vue";
import FormLabel from "./minerva/src/FormLabel.vue";
import MenuInline from "./minerva/src/MenuInline.vue";
import StatCard from "./minerva/src/StatCard.vue";
import Divider from "./minerva/src/Divider.vue";
import Empty from "./minerva/src/Empty.vue";
import Drawer from "./minerva/src/Drawer.vue";
import JsonField from "./minerva/src/JsonField.vue";
import DrawerClose from "./minerva/src/DrawerClose.vue";
import TimePicker from "./minerva/src/TimePicker.vue";
import Alert from "./minerva/src/Alert.vue";
import Tooltip from "./minerva/src/Tooltip.vue";
import Tag from "./minerva/src/Tag.vue";
import PageTab from "./minerva/src/PageTab.vue";
import FormErrorMessage from "./minerva/src/FormErrorMessage.vue";
import Switch from "./minerva/src/Switch.vue";
import ModalClose from "./minerva/src/ModalClose.vue";
import SelectGroup from "./minerva/src/SelectGroup.vue";
import Stack from "./minerva/src/Stack.vue";
import SkeletonText from "./minerva/src/SkeletonText.vue";
import CardHeader from "./minerva/src/CardHeader.vue";
import SelectSeparator from "./minerva/src/SelectSeparator.vue";
import VStack from "./minerva/src/VStack.vue";
import ContextMenu from "./minerva/src/ContextMenu.vue";
import DrawerHeader from "./minerva/src/DrawerHeader.vue";
import RatingScale from "./minerva/src/RatingScale.vue";
import TabList from "./minerva/src/TabList.vue";
import HtmlPreview from "./minerva/src/HtmlPreview.vue";
import TableCellContent from "./minerva/src/TableCellContent.vue";
import Avatar from "./minerva/src/Avatar.vue";
import HStack from "./minerva/src/HStack.vue";
import ThemeProvider from "./minerva/src/ThemeProvider.vue";
import TooltipProvider from "./minerva/src/TooltipProvider.vue";
import DrawerTrigger from "./minerva/src/DrawerTrigger.vue";
import ThemeToggle from "./minerva/src/ThemeToggle.vue";
import DrawerRoot from "./minerva/src/DrawerRoot.vue";
import DrawerFooter from "./minerva/src/DrawerFooter.vue";
import DataTable from "./minerva/src/DataTable.vue";
import CardFooter from "./minerva/src/CardFooter.vue";
import PopoverClose from "./minerva/src/PopoverClose.vue";
import DrawerContent from "./minerva/src/DrawerContent.vue";
import Upload from "./minerva/src/Upload.vue";
import Menu from "./minerva/src/Menu.vue";
import Confirm from "./minerva/src/Confirm.vue";
import ModalRoot from "./minerva/src/ModalRoot.vue";
import Box from "./minerva/src/Box.vue";
import Rating from "./minerva/src/Rating.vue";
import DescriptionList from "./minerva/src/DescriptionList.vue";
import ListItem from "./minerva/src/ListItem.vue";
import IconButton from "./minerva/src/IconButton.vue";
import Badge from "./minerva/src/Badge.vue";
import FormControl from "./minerva/src/FormControl.vue";
import PopoverAnchor from "./minerva/src/PopoverAnchor.vue";
import AvatarGroup from "./minerva/src/AvatarGroup.vue";
import PopoverContent from "./minerva/src/PopoverContent.vue";
import MenuEntries from "./minerva/src/MenuEntries.vue";
import ModalHeader from "./minerva/src/ModalHeader.vue";
import GridItem from "./minerva/src/GridItem.vue";
import Table from "./minerva/src/Table.vue";
import Button from "./minerva/src/Button.vue";
import NumberInput from "./minerva/src/NumberInput.vue";
import SplitLayout from "./minerva/src/SplitLayout.vue";
import TableBody from "./minerva/src/TableBody.vue";
import Toast from "./minerva/src/Toast.vue";
import PopoverTrigger from "./minerva/src/PopoverTrigger.vue";
import TextLink from "./minerva/src/TextLink.vue";
import CardDescription from "./minerva/src/CardDescription.vue";
import ProgressIndicator from "./minerva/src/ProgressIndicator.vue";
import Modal from "./minerva/src/Modal.vue";
import RadioGroup from "./minerva/src/RadioGroup.vue";
import ConfirmProvider from "./minerva/src/ConfirmProvider.vue";
import Page from "./minerva/src/Page.vue";
import Checkbox from "./minerva/src/Checkbox.vue";
import SelectLabel from "./minerva/src/SelectLabel.vue";
import TabPanel from "./minerva/src/TabPanel.vue";
import Textarea from "./minerva/src/Textarea.vue";
import Input from "./minerva/src/Input.vue";
import PaletteToggle from "./minerva/src/PaletteToggle.vue";
import Select from "./minerva/src/Select.vue";
import NavTree from "./minerva/src/NavTree.vue";
import Skeleton from "./minerva/src/Skeleton.vue";
import CodeBlock from "./minerva/src/CodeBlock.vue";
import ModalFooter from "./minerva/src/ModalFooter.vue";
import ConfigProvider from "./minerva/src/ConfigProvider.vue";
import AutoComplete from "./minerva/src/AutoComplete.vue";
import ResponsiveGrid from "./minerva/src/ResponsiveGrid.vue";
import LoadingState from "./minerva/src/LoadingState.vue";
export function createApp() {
  const app = createSSRApp(App);
  app.component("Steps", Steps);
  app.component("ConfirmDialog", ConfirmDialog);
  app.component("TableCell", TableCell);
  app.component("Pagination", Pagination);
  app.component("FormHelperText", FormHelperText);
  app.component("Cascader", Cascader);
  app.component("TableHead", TableHead);
  app.component("Tabs", Tabs);
  app.component("TableHeader", TableHeader);
  app.component("PageTabs", PageTabs);
  app.component("KeyValueEditor", KeyValueEditor);
  app.component("ModalBody", ModalBody);
  app.component("PageSection", PageSection);
  app.component("Prose", Prose);
  app.component("FormLayout", FormLayout);
  app.component("Popover", Popover);
  app.component("Card", Card);
  app.component("TableRoot", TableRoot);
  app.component("CardContent", CardContent);
  app.component("SelectItem", SelectItem);
  app.component("Radio", Radio);
  app.component("CommandDialog", CommandDialog);
  app.component("FormField", FormField);
  app.component("ModalContent", ModalContent);
  app.component("PageHeader", PageHeader);
  app.component("Tab", Tab);
  app.component("DrawerBody", DrawerBody);
  app.component("MonthCalendar", MonthCalendar);
  app.component("Toolbar", Toolbar);
  app.component("List", List);
  app.component("VirtualList", VirtualList);
  app.component("TagInput", TagInput);
  app.component("ModalTrigger", ModalTrigger);
  app.component("TableRow", TableRow);
  app.component("AppShell", AppShell);
  app.component("DialogSurface", DialogSurface);
  app.component("ToastProvider", ToastProvider);
  app.component("CardTitle", CardTitle);
  app.component("FormLabel", FormLabel);
  app.component("MenuInline", MenuInline);
  app.component("StatCard", StatCard);
  app.component("Divider", Divider);
  app.component("Empty", Empty);
  app.component("Drawer", Drawer);
  app.component("JsonField", JsonField);
  app.component("DrawerClose", DrawerClose);
  app.component("TimePicker", TimePicker);
  app.component("Alert", Alert);
  app.component("Tooltip", Tooltip);
  app.component("Tag", Tag);
  app.component("PageTab", PageTab);
  app.component("FormErrorMessage", FormErrorMessage);
  app.component("Switch", Switch);
  app.component("ModalClose", ModalClose);
  app.component("SelectGroup", SelectGroup);
  app.component("Stack", Stack);
  app.component("SkeletonText", SkeletonText);
  app.component("CardHeader", CardHeader);
  app.component("SelectSeparator", SelectSeparator);
  app.component("VStack", VStack);
  app.component("ContextMenu", ContextMenu);
  app.component("DrawerHeader", DrawerHeader);
  app.component("RatingScale", RatingScale);
  app.component("TabList", TabList);
  app.component("HtmlPreview", HtmlPreview);
  app.component("TableCellContent", TableCellContent);
  app.component("Avatar", Avatar);
  app.component("HStack", HStack);
  app.component("ThemeProvider", ThemeProvider);
  app.component("TooltipProvider", TooltipProvider);
  app.component("DrawerTrigger", DrawerTrigger);
  app.component("ThemeToggle", ThemeToggle);
  app.component("DrawerRoot", DrawerRoot);
  app.component("DrawerFooter", DrawerFooter);
  app.component("DataTable", DataTable);
  app.component("CardFooter", CardFooter);
  app.component("PopoverClose", PopoverClose);
  app.component("DrawerContent", DrawerContent);
  app.component("Upload", Upload);
  app.component("Menu", Menu);
  app.component("Confirm", Confirm);
  app.component("ModalRoot", ModalRoot);
  app.component("Box", Box);
  app.component("Rating", Rating);
  app.component("DescriptionList", DescriptionList);
  app.component("ListItem", ListItem);
  app.component("IconButton", IconButton);
  app.component("Badge", Badge);
  app.component("FormControl", FormControl);
  app.component("PopoverAnchor", PopoverAnchor);
  app.component("AvatarGroup", AvatarGroup);
  app.component("PopoverContent", PopoverContent);
  app.component("MenuEntries", MenuEntries);
  app.component("ModalHeader", ModalHeader);
  app.component("GridItem", GridItem);
  app.component("Table", Table);
  app.component("Button", Button);
  app.component("NumberInput", NumberInput);
  app.component("SplitLayout", SplitLayout);
  app.component("TableBody", TableBody);
  app.component("Toast", Toast);
  app.component("PopoverTrigger", PopoverTrigger);
  app.component("TextLink", TextLink);
  app.component("CardDescription", CardDescription);
  app.component("ProgressIndicator", ProgressIndicator);
  app.component("Modal", Modal);
  app.component("RadioGroup", RadioGroup);
  app.component("ConfirmProvider", ConfirmProvider);
  app.component("Page", Page);
  app.component("Checkbox", Checkbox);
  app.component("SelectLabel", SelectLabel);
  app.component("TabPanel", TabPanel);
  app.component("Textarea", Textarea);
  app.component("Input", Input);
  app.component("PaletteToggle", PaletteToggle);
  app.component("Select", Select);
  app.component("NavTree", NavTree);
  app.component("Skeleton", Skeleton);
  app.component("CodeBlock", CodeBlock);
  app.component("ModalFooter", ModalFooter);
  app.component("ConfigProvider", ConfigProvider);
  app.component("AutoComplete", AutoComplete);
  app.component("ResponsiveGrid", ResponsiveGrid);
  app.component("LoadingState", LoadingState);
  return { app };
}
