// Generated by scripts/generate-global.mjs: do not edit.
// Volar typings of the components registered by `app.use(MinervaVue)`
// (default prefix "Mn"): add "minerva-design/vue/global" to the "types" of
// tsconfig.json, or `import type {} from "minerva-design/vue/global"`.
import type * as Minerva from "./index";

declare module "vue" {
  export interface GlobalComponents {
    MnButton: typeof Minerva.Button;
    MnConfigProvider: typeof Minerva.ConfigProvider;
    MnModal: typeof Minerva.Modal;
    MnModalBody: typeof Minerva.ModalBody;
    MnModalClose: typeof Minerva.ModalClose;
    MnModalContent: typeof Minerva.ModalContent;
    MnModalFooter: typeof Minerva.ModalFooter;
    MnModalHeader: typeof Minerva.ModalHeader;
    MnModalRoot: typeof Minerva.ModalRoot;
    MnModalTrigger: typeof Minerva.ModalTrigger;
  }
}

export {};
