// Vite plugin of the docs site: `pages/<id>/wc/<demo>.html?wc-frameworks`
// exports the demo's source in every framework idiom
// (`{ vue, angular, svelte, solid, html }`), generated by ./transform.ts from
// the demo's HTML and its optional `wc/<demo>.ts` setup script.
import { existsSync, readFileSync } from "node:fs";
import { basename, dirname } from "node:path";
import type { Plugin } from "vite";
import { format } from "prettier";
import { formatWcSources, transformWcDemo } from "./transform.ts";

export const WC_FRAMEWORKS_QUERY = "wc-frameworks";

/** Framework sources of one demo file (formatted) */
export async function readWcFrameworkSources(
  file: string,
  onError?: (message: string) => void,
) {
  const scriptFile = file.replace(/\.html$/, ".ts");
  const script = existsSync(scriptFile)
    ? readFileSync(scriptFile, "utf8")
    : undefined;
  const { sources } = transformWcDemo({
    page: basename(dirname(dirname(file))),
    demo: basename(file, ".html"),
    html: readFileSync(file, "utf8"),
    script,
  });
  const formatted = await formatWcSources(sources, format, (fw, error) =>
    onError?.(`${file} (${fw}): ${String(error).split("\n")[0]}`),
  );
  return { sources: formatted, files: script ? [file, scriptFile] : [file] };
}

export const wcFrameworksPlugin = (): Plugin => ({
  name: "minerva-wc-frameworks",
  enforce: "pre",
  async load(id) {
    const [file, query = ""] = id.split("?");
    if (
      !file.endsWith(".html") ||
      !new URLSearchParams(query).has(WC_FRAMEWORKS_QUERY)
    ) {
      return undefined;
    }
    const { sources, files } = await readWcFrameworkSources(file, (message) =>
      this.warn(message),
    );
    for (const watched of files) this.addWatchFile(watched);
    return `export default ${JSON.stringify(sources)};`;
  },
});
