// Every TypeScript / TSX block of the READMEs type-checks against the
// package sources (resolved like a consumer's imports), and every HTML block
// only uses existing custom elements, attributes and attribute values.
import { describe, expect, it } from "vitest";
import ts from "typescript";
import { dirname } from "node:path";
import { MARKDOWN, at, codeBlocks, type CodeBlock } from "./utils";
import { htmlProblems } from "./html-check";

const PATHS: Record<string, string[]> = {
  "minerva-design": ["packages/react/src/index.ts"],
  "minerva-design/theme-utils": ["packages/react/src/theme-utils.ts"],
  "minerva-design/utils": ["packages/react/src/utils-entry.ts"],
  "minerva-design/monaco": ["packages/react/src/monaco.ts"],
  "minerva-design/*.css": ["packages/react/src/global.d.ts"],
  "minerva-design/web-components": ["packages/web-components/src/index.ts"],
  "minerva-design/web-components/*.css": ["packages/react/src/global.d.ts"],
  "minerva-design/web-components/*": [
    "packages/web-components/src/elements/*.ts",
  ],
  "minerva-design/core": ["packages/core/src/index.ts"],
  "minerva-design/styling-hooks": ["packages/core/src/styling-hooks/index.ts"],
  // the sources of minerva-design import the private core package
  "@minerva/core": ["packages/core/src/index.ts"],
};

/**
 * `/// <reference types="minerva-design/web-components/react" />` points at
 * typings generated by the build (checked by the package's `test:dist`).
 */
const GENERATED_TYPINGS =
  /^\s*\/\/\/ <reference types="minerva-design\/web-components\/\w+" \/>/gm;

/** Framework APIs the examples use (not dependencies of this repository) */
const FRAMEWORKS = `
declare module "next/headers" {
  export function headers(): Promise<Headers>;
}
`;

const tsBlocks = MARKDOWN.flatMap(codeBlocks).filter((b) =>
  ["ts", "tsx"].includes(b.lang),
);
const htmlBlocks = MARKDOWN.flatMap(codeBlocks).filter(
  (b) => b.lang === "html",
);

/** Virtual file of a block, next to its README so imports resolve from there */
const virtualName = (b: CodeBlock) =>
  at(dirname(b.file), `__readme_${b.line}.${b.lang}`);

function typeCheck(blocks: CodeBlock[]) {
  const options: ts.CompilerOptions = {
    target: ts.ScriptTarget.ES2022,
    module: ts.ModuleKind.ESNext,
    moduleResolution: ts.ModuleResolutionKind.Bundler,
    jsx: ts.JsxEmit.ReactJSX,
    lib: ["lib.es2022.d.ts", "lib.dom.d.ts", "lib.dom.iterable.d.ts"],
    types: [],
    strict: true,
    noEmit: true,
    skipLibCheck: true,
    isolatedModules: true,
    experimentalDecorators: true,
    useDefineForClassFields: false,
    resolveJsonModule: true,
    allowArbitraryExtensions: true,
    paths: Object.fromEntries(
      Object.entries(PATHS).map(([k, v]) => [k, v.map((p) => at(p))]),
    ),
  };
  const files = new Map(
    blocks.map((b) => [virtualName(b), b.code.replace(GENERATED_TYPINGS, "")]),
  );
  files.set(at("tests/docs/__frameworks.d.ts"), FRAMEWORKS);
  const host = ts.createCompilerHost(options);
  const { getSourceFile, fileExists, readFile } = host;
  host.getSourceFile = (name, language, ...rest) =>
    files.has(name)
      ? ts.createSourceFile(name, files.get(name)!, language, true)
      : getSourceFile.call(host, name, language, ...rest);
  host.fileExists = (name) => files.has(name) || fileExists.call(host, name);
  host.readFile = (name) => files.get(name) ?? readFile.call(host, name);
  const program = ts.createProgram(
    [...files.keys(), at("packages/react/src/global.d.ts")],
    options,
    host,
  );
  return blocks.map((b) => {
    const source = program.getSourceFile(virtualName(b))!;
    return ts.getPreEmitDiagnostics(program, source).map((d) => {
      const line = d.file?.getLineAndCharacterOfPosition(d.start ?? 0).line;
      const where =
        d.file === source
          ? `${b.file}:${b.line + 1 + (line ?? 0)}`
          : d.file?.fileName;
      return `${where}: ${ts.flattenDiagnosticMessageText(d.messageText, " ")}`;
    });
  });
}

describe("README code blocks", () => {
  it("has TypeScript and HTML examples to check", () => {
    expect(tsBlocks.length).toBeGreaterThan(15);
    expect(htmlBlocks.length).toBeGreaterThan(5);
  });

  it("every ts / tsx block type-checks", () => {
    expect(typeCheck(tsBlocks).flat()).toEqual([]);
  });

  it("every html block uses existing elements, attributes and values", () => {
    expect(
      htmlBlocks.flatMap((b) =>
        htmlProblems(b.code).map((p) => `${b.file}:${b.line}: ${p}`),
      ),
    ).toEqual([]);
  });

  it("the checker reports broken examples", () => {
    const broken: CodeBlock = {
      file: "README.md",
      line: 0,
      lang: "tsx",
      code: 'import { Buton } from "minerva-design";\nexport const a = <Buton />;\n',
    };
    expect(typeCheck([broken]).flat().join("\n")).toMatch(/Buton/);
    expect(htmlProblems("<minerva-buton></minerva-buton>")).toEqual([
      "unknown element <minerva-buton>",
    ]);
    expect(
      htmlProblems(
        '<minerva-button colour="primary" size="huge">x</minerva-button>',
      ),
    ).toEqual([
      '<minerva-button> has no attribute "colour"',
      '<minerva-button size="huge">: not one of "xsmall" | "small" | "medium" | "large" | "xlarge"',
    ]);
  });
});
