// Generated by packages/angular/scripts/styles.mjs from the React SCSS
// modules (packages/react/src/components/**/*.module.scss): do not edit.
// Unscoped class names (tests, like the React / Web Components tests); the
// package build replaces the values with the scoped names of
// `minerva-design/style.css` (scripts/build.mjs).

/** A class map of a SCSS module (class name -> class of the stylesheet) */
export type ClassMap<K extends string> = Readonly<Record<K, string>>;

/** components/Alert/alert.module.scss */
export const alertStyles: ClassMap<
  | "action"
  | "alert"
  | "alertBounce"
  | "alertFadeIn"
  | "alertSlideIn"
  | "alertZoom"
  | "animation-bounce"
  | "animation-fadeIn"
  | "animation-slideIn"
  | "animation-zoom"
  | "banner"
  | "closeButton"
  | "collapsible"
  | "content"
  | "danger"
  | "expandButton"
  | "expandContent"
  | "expanded"
  | "icon"
  | "info"
  | "large"
  | "medium"
  | "message"
  | "outline"
  | "rippleRect"
  | "rounded"
  | "small"
  | "solid"
  | "success"
  | "title"
  | "warning"
  | "withAnimation"
  | "withElevation"
> = {
  action: "action",
  alert: "alert",
  alertBounce: "alertBounce",
  alertFadeIn: "alertFadeIn",
  alertSlideIn: "alertSlideIn",
  alertZoom: "alertZoom",
  "animation-bounce": "animation-bounce",
  "animation-fadeIn": "animation-fadeIn",
  "animation-slideIn": "animation-slideIn",
  "animation-zoom": "animation-zoom",
  banner: "banner",
  closeButton: "closeButton",
  collapsible: "collapsible",
  content: "content",
  danger: "danger",
  expandButton: "expandButton",
  expandContent: "expandContent",
  expanded: "expanded",
  icon: "icon",
  info: "info",
  large: "large",
  medium: "medium",
  message: "message",
  outline: "outline",
  rippleRect: "rippleRect",
  rounded: "rounded",
  small: "small",
  solid: "solid",
  success: "success",
  title: "title",
  warning: "warning",
  withAnimation: "withAnimation",
  withElevation: "withElevation",
};

/** components/AppShell/appShell.module.scss */
export const appShellStyles: ClassMap<
  | "brand"
  | "brandIcon"
  | "brandLabel"
  | "content"
  | "control"
  | "drawer"
  | "drawerBody"
  | "drawerClose"
  | "drawerHeader"
  | "fade-in"
  | "header"
  | "headerActions"
  | "navigation"
  | "overlay"
  | "shell"
  | "sidebar"
  | "sidebarActions"
  | "skipLink"
  | "slide-in"
  | "slide-in-rtl"
  | "workspace"
> = {
  brand: "brand",
  brandIcon: "brandIcon",
  brandLabel: "brandLabel",
  content: "content",
  control: "control",
  drawer: "drawer",
  drawerBody: "drawerBody",
  drawerClose: "drawerClose",
  drawerHeader: "drawerHeader",
  "fade-in": "fade-in",
  header: "header",
  headerActions: "headerActions",
  navigation: "navigation",
  overlay: "overlay",
  shell: "shell",
  sidebar: "sidebar",
  sidebarActions: "sidebarActions",
  skipLink: "skipLink",
  "slide-in": "slide-in",
  "slide-in-rtl": "slide-in-rtl",
  workspace: "workspace",
};

/** components/AutoComplete/autoComplete.module.scss */
export const autoCompleteStyles: ClassMap<
  | "active"
  | "animated"
  | "autoComplete"
  | "basicOption"
  | "content"
  | "description"
  | "disabled"
  | "dropdown"
  | "empty"
  | "groupLabel"
  | "highlight"
  | "icon"
  | "label"
  | "loading"
  | "optionItem"
  | "optionList"
  | "popup"
  | "slideIn"
> = {
  active: "active",
  animated: "animated",
  autoComplete: "autoComplete",
  basicOption: "basicOption",
  content: "content",
  description: "description",
  disabled: "disabled",
  dropdown: "dropdown",
  empty: "empty",
  groupLabel: "groupLabel",
  highlight: "highlight",
  icon: "icon",
  label: "label",
  loading: "loading",
  optionItem: "optionItem",
  optionList: "optionList",
  popup: "popup",
  slideIn: "slideIn",
};

/** components/Avatar/avatar.module.scss */
export const avatarStyles: ClassMap<
  | "avatar"
  | "avatarImg"
  | "avatarText"
  | "circle"
  | "danger"
  | "info"
  | "large"
  | "medium"
  | "primary"
  | "rippleRect"
  | "rounded"
  | "secondary"
  | "small"
  | "square"
  | "stacked"
  | "success"
  | "warning"
  | "xlarge"
  | "xsmall"
  | "xxlarge"
> = {
  avatar: "avatar",
  avatarImg: "avatarImg",
  avatarText: "avatarText",
  circle: "circle",
  danger: "danger",
  info: "info",
  large: "large",
  medium: "medium",
  primary: "primary",
  rippleRect: "rippleRect",
  rounded: "rounded",
  secondary: "secondary",
  small: "small",
  square: "square",
  stacked: "stacked",
  success: "success",
  warning: "warning",
  xlarge: "xlarge",
  xsmall: "xsmall",
  xxlarge: "xxlarge",
};

/** components/Avatar/avatarGroup.module.scss */
export const avatarGroupStyles: ClassMap<
  "avatarGroup" | "avatarGroupItem" | "count"
> = {
  avatarGroup: "avatarGroup",
  avatarGroupItem: "avatarGroupItem",
  count: "count",
};

/** components/Badge/badge.module.scss */
export const badgeStyles: ClassMap<
  | "badge"
  | "badgeWrapper"
  | "bottom-left"
  | "bottom-right"
  | "content"
  | "danger"
  | "dot"
  | "icon"
  | "info"
  | "large"
  | "medium"
  | "neutral"
  | "outline"
  | "primary"
  | "small"
  | "standalone"
  | "subtle"
  | "success"
  | "top-left"
  | "top-right"
  | "warning"
> = {
  badge: "badge",
  badgeWrapper: "badgeWrapper",
  "bottom-left": "bottom-left",
  "bottom-right": "bottom-right",
  content: "content",
  danger: "danger",
  dot: "dot",
  icon: "icon",
  info: "info",
  large: "large",
  medium: "medium",
  neutral: "neutral",
  outline: "outline",
  primary: "primary",
  small: "small",
  standalone: "standalone",
  subtle: "subtle",
  success: "success",
  "top-left": "top-left",
  "top-right": "top-right",
  warning: "warning",
};

/** components/Button/button.module.scss */
export const buttonStyles: ClassMap<
  | "active"
  | "borderRadiusCircle"
  | "borderRadiusLarge"
  | "borderRadiusMedium"
  | "borderRadiusNone"
  | "borderRadiusSmall"
  | "borderRadiusSquare"
  | "circle"
  | "customButton"
  | "danger"
  | "fullWidth"
  | "hidden"
  | "icon"
  | "info"
  | "label"
  | "large"
  | "loading"
  | "loadingSpinner"
  | "medium"
  | "neutral"
  | "primary"
  | "rounded"
  | "small"
  | "spin"
  | "square"
  | "success"
  | "variant-ghost"
  | "variant-link"
  | "variant-outline"
  | "variant-solid"
  | "warning"
  | "xlarge"
  | "xsmall"
> = {
  active: "active",
  borderRadiusCircle: "borderRadiusCircle",
  borderRadiusLarge: "borderRadiusLarge",
  borderRadiusMedium: "borderRadiusMedium",
  borderRadiusNone: "borderRadiusNone",
  borderRadiusSmall: "borderRadiusSmall",
  borderRadiusSquare: "borderRadiusSquare",
  circle: "circle",
  customButton: "customButton",
  danger: "danger",
  fullWidth: "fullWidth",
  hidden: "hidden",
  icon: "icon",
  info: "info",
  label: "label",
  large: "large",
  loading: "loading",
  loadingSpinner: "loadingSpinner",
  medium: "medium",
  neutral: "neutral",
  primary: "primary",
  rounded: "rounded",
  small: "small",
  spin: "spin",
  square: "square",
  success: "success",
  "variant-ghost": "variant-ghost",
  "variant-link": "variant-link",
  "variant-outline": "variant-outline",
  "variant-solid": "variant-solid",
  warning: "warning",
  xlarge: "xlarge",
  xsmall: "xsmall",
};

/** components/Card/card.module.scss */
export const cardStyles: ClassMap<
  | "card"
  | "cardContent"
  | "cardDescription"
  | "cardFooter"
  | "cardHeader"
  | "cardTitle"
  | "default"
  | "elevated"
  | "fadeIn"
  | "filled"
  | "ghost"
  | "interactive"
  | "outline"
  | "pad-large"
  | "pad-medium"
  | "pad-none"
  | "pad-small"
  | "padded"
  | "slideIn"
  | "zoomIn"
> = {
  card: "card",
  cardContent: "cardContent",
  cardDescription: "cardDescription",
  cardFooter: "cardFooter",
  cardHeader: "cardHeader",
  cardTitle: "cardTitle",
  default: "default",
  elevated: "elevated",
  fadeIn: "fadeIn",
  filled: "filled",
  ghost: "ghost",
  interactive: "interactive",
  outline: "outline",
  "pad-large": "pad-large",
  "pad-medium": "pad-medium",
  "pad-none": "pad-none",
  "pad-small": "pad-small",
  padded: "padded",
  slideIn: "slideIn",
  zoomIn: "zoomIn",
};

/** components/Cascader/cascader.module.scss */
export const cascaderStyles: ClassMap<
  | "active"
  | "arrow"
  | "cascader"
  | "clearIcon"
  | "column"
  | "disabled"
  | "dropdown"
  | "empty"
  | "expandIcon"
  | "focused"
  | "icon"
  | "input"
  | "label"
  | "loadingIndicator"
  | "open"
  | "option"
  | "panel"
  | "rotating"
  | "searchOption"
  | "searchResults"
  | "selector"
> = {
  active: "active",
  arrow: "arrow",
  cascader: "cascader",
  clearIcon: "clearIcon",
  column: "column",
  disabled: "disabled",
  dropdown: "dropdown",
  empty: "empty",
  expandIcon: "expandIcon",
  focused: "focused",
  icon: "icon",
  input: "input",
  label: "label",
  loadingIndicator: "loadingIndicator",
  open: "open",
  option: "option",
  panel: "panel",
  rotating: "rotating",
  searchOption: "searchOption",
  searchResults: "searchResults",
  selector: "selector",
};

/** components/Checkbox/checkbox.module.scss */
export const checkboxStyles: ClassMap<
  | "checkbox"
  | "checkboxWrapper"
  | "checkmark"
  | "circle"
  | "colorDanger"
  | "colorInfo"
  | "colorSuccess"
  | "colorWarning"
  | "disabled"
  | "error"
  | "errorIcon"
  | "errorText"
  | "helperText"
  | "helperTextWrapper"
  | "input"
  | "label"
  | "labelBottom"
  | "labelStart"
  | "labelTop"
  | "large"
  | "rippleRect"
  | "rounded"
  | "shake"
  | "small"
  | "square"
> = {
  checkbox: "checkbox",
  checkboxWrapper: "checkboxWrapper",
  checkmark: "checkmark",
  circle: "circle",
  colorDanger: "colorDanger",
  colorInfo: "colorInfo",
  colorSuccess: "colorSuccess",
  colorWarning: "colorWarning",
  disabled: "disabled",
  error: "error",
  errorIcon: "errorIcon",
  errorText: "errorText",
  helperText: "helperText",
  helperTextWrapper: "helperTextWrapper",
  input: "input",
  label: "label",
  labelBottom: "labelBottom",
  labelStart: "labelStart",
  labelTop: "labelTop",
  large: "large",
  rippleRect: "rippleRect",
  rounded: "rounded",
  shake: "shake",
  small: "small",
  square: "square",
};

/** components/CodeBlock/codeBlock.module.scss */
export const codeBlockStyles: ClassMap<
  "actions" | "codeBlock" | "copyable" | "root" | "visuallyHidden"
> = {
  actions: "actions",
  codeBlock: "codeBlock",
  copyable: "copyable",
  root: "root",
  visuallyHidden: "visuallyHidden",
};

/** components/Command/command.module.scss */
export const commandStyles: ClassMap<
  | "copy"
  | "dialog"
  | "empty"
  | "enterHint"
  | "group"
  | "header"
  | "input"
  | "item"
  | "kbd"
  | "results"
  | "search"
  | "searchIcon"
> = {
  copy: "copy",
  dialog: "dialog",
  empty: "empty",
  enterHint: "enterHint",
  group: "group",
  header: "header",
  input: "input",
  item: "item",
  kbd: "kbd",
  results: "results",
  search: "search",
  searchIcon: "searchIcon",
};

/** components/DescriptionList/descriptionList.module.scss */
export const descriptionListStyles: ClassMap<
  "bordered" | "descriptionList" | "row" | "striped"
> = {
  bordered: "bordered",
  descriptionList: "descriptionList",
  row: "row",
  striped: "striped",
};

/** components/Divider/divider.module.scss */
export const dividerStyles: ClassMap<
  | "dashed"
  | "divider"
  | "dotted"
  | "elevation"
  | "flexItem"
  | "horizontal"
  | "ripple"
  | "solid"
  | "text"
  | "textLeft"
  | "textRight"
  | "vertical"
  | "withText"
> = {
  dashed: "dashed",
  divider: "divider",
  dotted: "dotted",
  elevation: "elevation",
  flexItem: "flexItem",
  horizontal: "horizontal",
  ripple: "ripple",
  solid: "solid",
  text: "text",
  textLeft: "textLeft",
  textRight: "textRight",
  vertical: "vertical",
  withText: "withText",
};

/** components/Drawer/drawer.module.scss */
export const drawerStyles: ClassMap<
  | "body"
  | "bottom"
  | "close"
  | "content"
  | "description"
  | "drawer-fade-in"
  | "drawer-fade-out"
  | "drawer-slide-bottom-in"
  | "drawer-slide-bottom-out"
  | "drawer-slide-left-in"
  | "drawer-slide-left-out"
  | "drawer-slide-right-in"
  | "drawer-slide-right-out"
  | "drawer-slide-top-in"
  | "drawer-slide-top-out"
  | "footer"
  | "full"
  | "header"
  | "large"
  | "left"
  | "medium"
  | "overlay"
  | "right"
  | "small"
  | "top"
  | "visuallyHidden"
> = {
  body: "body",
  bottom: "bottom",
  close: "close",
  content: "content",
  description: "description",
  "drawer-fade-in": "drawer-fade-in",
  "drawer-fade-out": "drawer-fade-out",
  "drawer-slide-bottom-in": "drawer-slide-bottom-in",
  "drawer-slide-bottom-out": "drawer-slide-bottom-out",
  "drawer-slide-left-in": "drawer-slide-left-in",
  "drawer-slide-left-out": "drawer-slide-left-out",
  "drawer-slide-right-in": "drawer-slide-right-in",
  "drawer-slide-right-out": "drawer-slide-right-out",
  "drawer-slide-top-in": "drawer-slide-top-in",
  "drawer-slide-top-out": "drawer-slide-top-out",
  footer: "footer",
  full: "full",
  header: "header",
  large: "large",
  left: "left",
  medium: "medium",
  overlay: "overlay",
  right: "right",
  small: "small",
  top: "top",
  visuallyHidden: "visuallyHidden",
};

/** components/Empty/empty.module.scss */
export const emptyStyles: ClassMap<
  | "actions"
  | "defaultIcon"
  | "description"
  | "empty"
  | "footer"
  | "iconWrapper"
  | "rippleRect"
  | "showShadow"
  | "size-large"
  | "size-medium"
  | "size-small"
  | "sized"
  | "svgFill"
  | "svgPath"
  | "svgStroke"
  | "title"
> = {
  actions: "actions",
  defaultIcon: "defaultIcon",
  description: "description",
  empty: "empty",
  footer: "footer",
  iconWrapper: "iconWrapper",
  rippleRect: "rippleRect",
  showShadow: "showShadow",
  "size-large": "size-large",
  "size-medium": "size-medium",
  "size-small": "size-small",
  sized: "sized",
  svgFill: "svgFill",
  svgPath: "svgPath",
  svgStroke: "svgStroke",
  title: "title",
};

/** components/FormControl/formControl.module.scss */
export const formControlStyles: ClassMap<
  "error" | "helper" | "label" | "required" | "root"
> = {
  error: "error",
  helper: "helper",
  label: "label",
  required: "required",
  root: "root",
};

/** components/FormLayout/formLayout.module.scss */
export const formLayoutStyles: ClassMap<"root"> = {
  root: "root",
};

/** components/HtmlPreview/htmlPreview.module.scss */
export const htmlPreviewStyles: ClassMap<"frame" | "preview"> = {
  frame: "frame",
  preview: "preview",
};

/** components/IconButton/iconButton.module.scss */
export const iconButtonStyles: ClassMap<
  | "circle"
  | "danger"
  | "disabled"
  | "glyph"
  | "iconButton"
  | "info"
  | "large"
  | "loading"
  | "medium"
  | "neutral"
  | "pressed"
  | "primary"
  | "rippleRect"
  | "small"
  | "square"
  | "success"
  | "variant-ghost"
  | "variant-outline"
  | "variant-solid"
  | "warning"
  | "xsmall"
> = {
  circle: "circle",
  danger: "danger",
  disabled: "disabled",
  glyph: "glyph",
  iconButton: "iconButton",
  info: "info",
  large: "large",
  loading: "loading",
  medium: "medium",
  neutral: "neutral",
  pressed: "pressed",
  primary: "primary",
  rippleRect: "rippleRect",
  small: "small",
  square: "square",
  success: "success",
  "variant-ghost": "variant-ghost",
  "variant-outline": "variant-outline",
  "variant-solid": "variant-solid",
  warning: "warning",
  xsmall: "xsmall",
};

/** components/Input/input.module.scss */
export const inputStyles: ClassMap<
  | "action"
  | "addon"
  | "count"
  | "disabled"
  | "end"
  | "field"
  | "filled"
  | "invalid"
  | "large"
  | "medium"
  | "outline"
  | "root"
  | "small"
  | "start"
  | "unstyled"
> = {
  action: "action",
  addon: "addon",
  count: "count",
  disabled: "disabled",
  end: "end",
  field: "field",
  filled: "filled",
  invalid: "invalid",
  large: "large",
  medium: "medium",
  outline: "outline",
  root: "root",
  small: "small",
  start: "start",
  unstyled: "unstyled",
};

/** components/JsonField/jsonField.module.scss */
export const jsonFieldStyles: ClassMap<
  "root" | "status" | "statusInvalid" | "textarea" | "toolbar"
> = {
  root: "root",
  status: "status",
  statusInvalid: "statusInvalid",
  textarea: "textarea",
  toolbar: "toolbar",
};

/** components/KeyValueEditor/keyValueEditor.module.scss */
export const keyValueEditorStyles: ClassMap<
  "add" | "key" | "remove" | "root" | "row" | "srOnly"
> = {
  add: "add",
  key: "key",
  remove: "remove",
  root: "root",
  row: "row",
  srOnly: "srOnly",
};

/** components/List/list.module.scss */
export const listStyles: ClassMap<
  | "actions"
  | "bordered"
  | "comfortable"
  | "compact"
  | "content"
  | "dividers"
  | "icon"
  | "item"
  | "list"
  | "primary"
  | "secondary"
> = {
  actions: "actions",
  bordered: "bordered",
  comfortable: "comfortable",
  compact: "compact",
  content: "content",
  dividers: "dividers",
  icon: "icon",
  item: "item",
  list: "list",
  primary: "primary",
  secondary: "secondary",
};

/** components/LoadingState/loadingState.module.scss */
export const loadingStateStyles: ClassMap<
  "indicator" | "label" | "large" | "loadingState" | "medium" | "small"
> = {
  indicator: "indicator",
  label: "label",
  large: "large",
  loadingState: "loadingState",
  medium: "medium",
  small: "small",
};

/** components/Menu/menu.module.scss */
export const menuStyles: ClassMap<
  | "chevron"
  | "content"
  | "dot"
  | "icon"
  | "indicator"
  | "item"
  | "label"
  | "menu-fade-in"
  | "menu-fade-out"
  | "separator"
  | "shortcut"
  | "small"
  | "text"
> = {
  chevron: "chevron",
  content: "content",
  dot: "dot",
  icon: "icon",
  indicator: "indicator",
  item: "item",
  label: "label",
  "menu-fade-in": "menu-fade-in",
  "menu-fade-out": "menu-fade-out",
  separator: "separator",
  shortcut: "shortcut",
  small: "small",
  text: "text",
};

/** components/Modal/modal.module.scss */
export const modalStyles: ClassMap<
  | "body"
  | "close"
  | "content"
  | "description"
  | "footer"
  | "full"
  | "header"
  | "large"
  | "medium"
  | "modal-fade-in"
  | "modal-fade-out"
  | "modal-slide-down"
  | "modal-slide-up"
  | "modal-zoom-in"
  | "modal-zoom-out"
  | "overlay"
  | "small"
  | "visuallyHidden"
  | "xlarge"
> = {
  body: "body",
  close: "close",
  content: "content",
  description: "description",
  footer: "footer",
  full: "full",
  header: "header",
  large: "large",
  medium: "medium",
  "modal-fade-in": "modal-fade-in",
  "modal-fade-out": "modal-fade-out",
  "modal-slide-down": "modal-slide-down",
  "modal-slide-up": "modal-slide-up",
  "modal-zoom-in": "modal-zoom-in",
  "modal-zoom-out": "modal-zoom-out",
  overlay: "overlay",
  small: "small",
  visuallyHidden: "visuallyHidden",
  xlarge: "xlarge",
};

/** components/MonacoCodeEditor/monacoCodeEditor.module.scss */
export const monacoCodeEditorStyles: ClassMap<
  | "error"
  | "fallback"
  | "label"
  | "loading"
  | "message"
  | "retryIcon"
  | "root"
  | "surface"
> = {
  error: "error",
  fallback: "fallback",
  label: "label",
  loading: "loading",
  message: "message",
  retryIcon: "retryIcon",
  root: "root",
  surface: "surface",
};

/** components/MonthCalendar/monthCalendar.module.scss */
export const monthCalendarStyles: ClassMap<
  | "count"
  | "day"
  | "dayNumber"
  | "empty"
  | "eventButton"
  | "eventItem"
  | "eventList"
  | "events"
  | "eventsHeading"
  | "grid"
  | "hasEvents"
  | "heading"
  | "iconButton"
  | "inRange"
  | "large"
  | "monthCalendar"
  | "navButton"
  | "navigation"
  | "rangeEnd"
  | "rangeStart"
  | "small"
  | "toolbar"
  | "week"
  | "weekday"
> = {
  count: "count",
  day: "day",
  dayNumber: "dayNumber",
  empty: "empty",
  eventButton: "eventButton",
  eventItem: "eventItem",
  eventList: "eventList",
  events: "events",
  eventsHeading: "eventsHeading",
  grid: "grid",
  hasEvents: "hasEvents",
  heading: "heading",
  iconButton: "iconButton",
  inRange: "inRange",
  large: "large",
  monthCalendar: "monthCalendar",
  navButton: "navButton",
  navigation: "navigation",
  rangeEnd: "rangeEnd",
  rangeStart: "rangeStart",
  small: "small",
  toolbar: "toolbar",
  week: "week",
  weekday: "weekday",
};

/** components/NavTree/navTree.module.scss */
export const navTreeStyles: ClassMap<
  | "active"
  | "branch"
  | "chevron"
  | "children"
  | "collapsed"
  | "copy"
  | "description"
  | "disabled"
  | "end"
  | "icon"
  | "item"
  | "label"
  | "list"
  | "navTree"
  | "nested"
  | "section"
  | "sectionTitle"
  | "trailing"
  | "wrapLabels"
> = {
  active: "active",
  branch: "branch",
  chevron: "chevron",
  children: "children",
  collapsed: "collapsed",
  copy: "copy",
  description: "description",
  disabled: "disabled",
  end: "end",
  icon: "icon",
  item: "item",
  label: "label",
  list: "list",
  navTree: "navTree",
  nested: "nested",
  section: "section",
  sectionTitle: "sectionTitle",
  trailing: "trailing",
  wrapLabels: "wrapLabels",
};

/** components/NumberInput/numberInput.module.scss */
export const numberInputStyles: ClassMap<
  | "disabled"
  | "field"
  | "invalid"
  | "large"
  | "medium"
  | "number-input-shake"
  | "root"
  | "shake"
  | "small"
  | "step"
  | "stepDown"
  | "stepUp"
  | "stepper"
> = {
  disabled: "disabled",
  field: "field",
  invalid: "invalid",
  large: "large",
  medium: "medium",
  "number-input-shake": "number-input-shake",
  root: "root",
  shake: "shake",
  small: "small",
  step: "step",
  stepDown: "stepDown",
  stepUp: "stepUp",
  stepper: "stepper",
};

/** components/Page/page.module.scss */
export const pageStyles: ClassMap<
  | "actions"
  | "compact"
  | "header"
  | "heading"
  | "nowrap"
  | "page"
  | "section"
  | "sectionHeader"
  | "sectionIcon"
  | "statCard"
  | "statContent"
  | "statDescription"
  | "statIcon"
  | "toolbar"
> = {
  actions: "actions",
  compact: "compact",
  header: "header",
  heading: "heading",
  nowrap: "nowrap",
  page: "page",
  section: "section",
  sectionHeader: "sectionHeader",
  sectionIcon: "sectionIcon",
  statCard: "statCard",
  statContent: "statContent",
  statDescription: "statDescription",
  statIcon: "statIcon",
  toolbar: "toolbar",
};

/** components/PageTabs/pageTabs.module.scss */
export const pageTabsStyles: ClassMap<
  | "action"
  | "actions"
  | "icon"
  | "label"
  | "list"
  | "pageTab"
  | "pageTabs"
  | "scroll"
  | "trigger"
  | "viewport"
> = {
  action: "action",
  actions: "actions",
  icon: "icon",
  label: "label",
  list: "list",
  pageTab: "pageTab",
  pageTabs: "pageTabs",
  scroll: "scroll",
  trigger: "trigger",
  viewport: "viewport",
};

/** components/Pagination/pagination.module.scss */
export const paginationStyles: ClassMap<
  | "active"
  | "circle"
  | "counter"
  | "disabled"
  | "ellipsis"
  | "ghost"
  | "item"
  | "jump"
  | "jumpHint"
  | "jumpWrapper"
  | "jumper"
  | "large"
  | "next"
  | "outline"
  | "pagination"
  | "prev"
  | "responsive"
  | "ripple"
  | "simpleDivider"
  | "simpleInput"
  | "sizeChanger"
  | "small"
  | "square"
  | "total"
> = {
  active: "active",
  circle: "circle",
  counter: "counter",
  disabled: "disabled",
  ellipsis: "ellipsis",
  ghost: "ghost",
  item: "item",
  jump: "jump",
  jumpHint: "jumpHint",
  jumpWrapper: "jumpWrapper",
  jumper: "jumper",
  large: "large",
  next: "next",
  outline: "outline",
  pagination: "pagination",
  prev: "prev",
  responsive: "responsive",
  ripple: "ripple",
  simpleDivider: "simpleDivider",
  simpleInput: "simpleInput",
  sizeChanger: "sizeChanger",
  small: "small",
  square: "square",
  total: "total",
};

/** components/Popover/popover.module.scss */
export const popoverStyles: ClassMap<
  | "arrow"
  | "arrowWrapper"
  | "content"
  | "popover-fade-in"
  | "popover-fade-out"
  | "positioner"
> = {
  arrow: "arrow",
  arrowWrapper: "arrowWrapper",
  content: "content",
  "popover-fade-in": "popover-fade-in",
  "popover-fade-out": "popover-fade-out",
  positioner: "positioner",
};

/** components/ProgressIndicator/progressIndicator.module.scss */
export const progressIndicatorStyles: ClassMap<
  | "bar"
  | "barAnimation"
  | "barContainer"
  | "circle"
  | "current"
  | "defaultWidth"
  | "dottedBar"
  | "dottedBarAnimation"
  | "dottedBarContainer"
  | "fullWidth"
  | "icon"
  | "label"
  | "large"
  | "medium"
  | "neutral"
  | "primary"
  | "progressIndicator"
  | "small"
  | "spin"
  | "spinner"
  | "wave"
  | "waveAnimation"
  | "waveContainer"
  | "xlarge"
  | "xsmall"
> = {
  bar: "bar",
  barAnimation: "barAnimation",
  barContainer: "barContainer",
  circle: "circle",
  current: "current",
  defaultWidth: "defaultWidth",
  dottedBar: "dottedBar",
  dottedBarAnimation: "dottedBarAnimation",
  dottedBarContainer: "dottedBarContainer",
  fullWidth: "fullWidth",
  icon: "icon",
  label: "label",
  large: "large",
  medium: "medium",
  neutral: "neutral",
  primary: "primary",
  progressIndicator: "progressIndicator",
  small: "small",
  spin: "spin",
  spinner: "spinner",
  wave: "wave",
  waveAnimation: "waveAnimation",
  waveContainer: "waveContainer",
  xlarge: "xlarge",
  xsmall: "xsmall",
};

/** components/Prose/prose.module.scss */
export const proseStyles: ClassMap<"prose"> = {
  prose: "prose",
};

/** components/Radio/radio.module.scss */
export const radioStyles: ClassMap<
  | "circle"
  | "danger"
  | "disabled"
  | "error"
  | "errorIcon"
  | "errorText"
  | "groupLabel"
  | "helperText"
  | "helperTextWrapper"
  | "horizontal"
  | "input"
  | "label"
  | "labelBottom"
  | "labelStart"
  | "labelTop"
  | "large"
  | "medium"
  | "primary"
  | "radio"
  | "radioGroup"
  | "radioGroupWrapper"
  | "radioMark"
  | "radioWrapper"
  | "rounded"
  | "shake"
  | "small"
  | "square"
  | "success"
  | "vertical"
  | "warning"
> = {
  circle: "circle",
  danger: "danger",
  disabled: "disabled",
  error: "error",
  errorIcon: "errorIcon",
  errorText: "errorText",
  groupLabel: "groupLabel",
  helperText: "helperText",
  helperTextWrapper: "helperTextWrapper",
  horizontal: "horizontal",
  input: "input",
  label: "label",
  labelBottom: "labelBottom",
  labelStart: "labelStart",
  labelTop: "labelTop",
  large: "large",
  medium: "medium",
  primary: "primary",
  radio: "radio",
  radioGroup: "radioGroup",
  radioGroupWrapper: "radioGroupWrapper",
  radioMark: "radioMark",
  radioWrapper: "radioWrapper",
  rounded: "rounded",
  shake: "shake",
  small: "small",
  square: "square",
  success: "success",
  vertical: "vertical",
  warning: "warning",
};

/** components/Rating/rating.module.scss */
export const ratingStyles: ClassMap<
  | "count"
  | "empty"
  | "half"
  | "halfBase"
  | "halfFill"
  | "interactive"
  | "large"
  | "rating"
  | "scale"
  | "scaleLabel"
  | "scaleRow"
  | "small"
  | "star"
  | "starButton"
  | "stars"
  | "value"
> = {
  count: "count",
  empty: "empty",
  half: "half",
  halfBase: "halfBase",
  halfFill: "halfFill",
  interactive: "interactive",
  large: "large",
  rating: "rating",
  scale: "scale",
  scaleLabel: "scaleLabel",
  scaleRow: "scaleRow",
  small: "small",
  star: "star",
  starButton: "starButton",
  stars: "stars",
  value: "value",
};

/** components/ResponsiveGrid/responsiveGrid.module.scss */
export const responsiveGridStyles: ClassMap<
  "fullWidth" | "item" | "layout" | "root"
> = {
  fullWidth: "fullWidth",
  item: "item",
  layout: "layout",
  root: "root",
};

/** components/Select/select.module.scss */
export const selectStyles: ClassMap<
  | "content"
  | "icon"
  | "invalid"
  | "item"
  | "itemIndicator"
  | "itemText"
  | "label"
  | "large"
  | "medium"
  | "positioner"
  | "selectFadeIn"
  | "selectFadeInUp"
  | "separator"
  | "small"
  | "trigger"
  | "value"
> = {
  content: "content",
  icon: "icon",
  invalid: "invalid",
  item: "item",
  itemIndicator: "itemIndicator",
  itemText: "itemText",
  label: "label",
  large: "large",
  medium: "medium",
  positioner: "positioner",
  selectFadeIn: "selectFadeIn",
  selectFadeInUp: "selectFadeInUp",
  separator: "separator",
  small: "small",
  trigger: "trigger",
  value: "value",
};

/** components/Skeleton/skeleton.module.scss */
export const skeletonStyles: ClassMap<
  | "active"
  | "animation-pulse"
  | "animation-wave"
  | "avatar"
  | "avatar-circle"
  | "avatar-square"
  | "button"
  | "card"
  | "cardContent"
  | "circular"
  | "content"
  | "decorative"
  | "image"
  | "paragraph"
  | "pulse"
  | "rectangular"
  | "rounded"
  | "skeleton"
  | "skeletonRoot"
  | "skeletonText"
  | "text"
  | "title"
  | "wave"
  | "withAvatar"
> = {
  active: "active",
  "animation-pulse": "animation-pulse",
  "animation-wave": "animation-wave",
  avatar: "avatar",
  "avatar-circle": "avatar-circle",
  "avatar-square": "avatar-square",
  button: "button",
  card: "card",
  cardContent: "cardContent",
  circular: "circular",
  content: "content",
  decorative: "decorative",
  image: "image",
  paragraph: "paragraph",
  pulse: "pulse",
  rectangular: "rectangular",
  rounded: "rounded",
  skeleton: "skeleton",
  skeletonRoot: "skeletonRoot",
  skeletonText: "skeletonText",
  text: "text",
  title: "title",
  wave: "wave",
  withAvatar: "withAvatar",
};

/** components/SplitLayout/splitLayout.module.scss */
export const splitLayoutStyles: ClassMap<
  "aside" | "grid" | "hasAside" | "lg" | "main" | "md" | "root"
> = {
  aside: "aside",
  grid: "grid",
  hasAside: "hasAside",
  lg: "lg",
  main: "main",
  md: "md",
  root: "root",
};

/** components/Stack/stack.module.scss */
export const stackStyles: ClassMap<
  | "attached"
  | "column"
  | "column-reverse"
  | "row"
  | "row-reverse"
  | "stack"
  | "wrap"
> = {
  attached: "attached",
  column: "column",
  "column-reverse": "column-reverse",
  row: "row",
  "row-reverse": "row-reverse",
  stack: "stack",
  wrap: "wrap",
};

/** components/Steps/steps.module.scss */
export const stepsStyles: ClassMap<
  "button" | "complete" | "current" | "number" | "static" | "step" | "steps"
> = {
  button: "button",
  complete: "complete",
  current: "current",
  number: "number",
  static: "static",
  step: "step",
  steps: "steps",
};

/** components/Switch/switch.module.scss */
export const switchStyles: ClassMap<
  | "bilateral"
  | "checked"
  | "checkedLarge"
  | "danger"
  | "disabled"
  | "hiddenInput"
  | "icon"
  | "info"
  | "label"
  | "labelBottom"
  | "labelEnd"
  | "labelStart"
  | "labelTop"
  | "large"
  | "loading"
  | "loadingIcon"
  | "primary"
  | "ripple"
  | "rippleEffect"
  | "segment"
  | "segmentActive"
  | "segmented"
  | "side"
  | "sideActive"
  | "small"
  | "square"
  | "success"
  | "switch"
  | "switchBase"
  | "switchLoading"
  | "thumb"
  | "track"
  | "warning"
> = {
  bilateral: "bilateral",
  checked: "checked",
  checkedLarge: "checkedLarge",
  danger: "danger",
  disabled: "disabled",
  hiddenInput: "hiddenInput",
  icon: "icon",
  info: "info",
  label: "label",
  labelBottom: "labelBottom",
  labelEnd: "labelEnd",
  labelStart: "labelStart",
  labelTop: "labelTop",
  large: "large",
  loading: "loading",
  loadingIcon: "loadingIcon",
  primary: "primary",
  ripple: "ripple",
  rippleEffect: "rippleEffect",
  segment: "segment",
  segmentActive: "segmentActive",
  segmented: "segmented",
  side: "side",
  sideActive: "sideActive",
  small: "small",
  square: "square",
  success: "success",
  switch: "switch",
  switchBase: "switchBase",
  switchLoading: "switchLoading",
  thumb: "thumb",
  track: "track",
  warning: "warning",
};

/** components/Table/table.module.scss */
export const tableStyles: ClassMap<
  | "cellContent"
  | "cellMono"
  | "cellPrimary"
  | "cellSecondary"
  | "cellStrong"
  | "checkbox"
  | "dataTable"
  | "empty"
  | "error"
  | "errorTitle"
  | "hoverable"
  | "large"
  | "medium"
  | "retryIcon"
  | "scrollX"
  | "selectionCell"
  | "skeleton"
  | "small"
  | "sortButton"
  | "sortIcon"
  | "sortLabel"
  | "striped"
  | "table"
  | "tableSkeletonPulse"
  | "wrapper"
  | "wrapperBordered"
  | "wrapperScrollY"
> = {
  cellContent: "cellContent",
  cellMono: "cellMono",
  cellPrimary: "cellPrimary",
  cellSecondary: "cellSecondary",
  cellStrong: "cellStrong",
  checkbox: "checkbox",
  dataTable: "dataTable",
  empty: "empty",
  error: "error",
  errorTitle: "errorTitle",
  hoverable: "hoverable",
  large: "large",
  medium: "medium",
  retryIcon: "retryIcon",
  scrollX: "scrollX",
  selectionCell: "selectionCell",
  skeleton: "skeleton",
  small: "small",
  sortButton: "sortButton",
  sortIcon: "sortIcon",
  sortLabel: "sortLabel",
  striped: "striped",
  table: "table",
  tableSkeletonPulse: "tableSkeletonPulse",
  wrapper: "wrapper",
  wrapperBordered: "wrapperBordered",
  wrapperScrollY: "wrapperScrollY",
};

/** components/Tabs/tabs.module.scss */
export const tabsStyles: ClassMap<
  | "colored"
  | "danger"
  | "enclosedList"
  | "enclosedTrigger"
  | "info"
  | "lineList"
  | "lineTrigger"
  | "list"
  | "neutral"
  | "panel"
  | "pillsList"
  | "pillsTrigger"
  | "primary"
  | "softList"
  | "softTrigger"
  | "success"
  | "tabs"
  | "trigger"
  | "vertical"
  | "verticalList"
  | "verticalTrigger"
  | "warning"
> = {
  colored: "colored",
  danger: "danger",
  enclosedList: "enclosedList",
  enclosedTrigger: "enclosedTrigger",
  info: "info",
  lineList: "lineList",
  lineTrigger: "lineTrigger",
  list: "list",
  neutral: "neutral",
  panel: "panel",
  pillsList: "pillsList",
  pillsTrigger: "pillsTrigger",
  primary: "primary",
  softList: "softList",
  softTrigger: "softTrigger",
  success: "success",
  tabs: "tabs",
  trigger: "trigger",
  vertical: "vertical",
  verticalList: "verticalList",
  verticalTrigger: "verticalTrigger",
  warning: "warning",
};

/** components/Tag/tag.module.scss */
export const tagStyles: ClassMap<
  | "action"
  | "avatar"
  | "circle"
  | "clickable"
  | "closeIcon"
  | "content"
  | "danger"
  | "disabled"
  | "elevation"
  | "icon"
  | "info"
  | "large"
  | "loading"
  | "medium"
  | "neutral"
  | "outline"
  | "pressed"
  | "primary"
  | "ripple"
  | "rippleAnimation"
  | "rounded"
  | "small"
  | "solid"
  | "spinner"
  | "square"
  | "success"
  | "tag"
  | "tagSpin"
  | "warning"
> = {
  action: "action",
  avatar: "avatar",
  circle: "circle",
  clickable: "clickable",
  closeIcon: "closeIcon",
  content: "content",
  danger: "danger",
  disabled: "disabled",
  elevation: "elevation",
  icon: "icon",
  info: "info",
  large: "large",
  loading: "loading",
  medium: "medium",
  neutral: "neutral",
  outline: "outline",
  pressed: "pressed",
  primary: "primary",
  ripple: "ripple",
  rippleAnimation: "rippleAnimation",
  rounded: "rounded",
  small: "small",
  solid: "solid",
  spinner: "spinner",
  square: "square",
  success: "success",
  tag: "tag",
  tagSpin: "tagSpin",
  warning: "warning",
};

/** components/TagInput/tagInput.module.scss */
export const tagInputStyles: ClassMap<
  | "combobox"
  | "empty"
  | "entry"
  | "label"
  | "list"
  | "option"
  | "root"
  | "tag"
  | "values"
> = {
  combobox: "combobox",
  empty: "empty",
  entry: "entry",
  label: "label",
  list: "list",
  option: "option",
  root: "root",
  tag: "tag",
  values: "values",
};

/** components/TextLink/textLink.module.scss */
export const textLinkStyles: ClassMap<"action" | "subtle" | "textLink"> = {
  action: "action",
  subtle: "subtle",
  textLink: "textLink",
};

/** components/Textarea/textarea.module.scss */
export const textareaStyles: ClassMap<
  | "filled"
  | "invalid"
  | "large"
  | "medium"
  | "outline"
  | "small"
  | "textarea"
  | "unstyled"
> = {
  filled: "filled",
  invalid: "invalid",
  large: "large",
  medium: "medium",
  outline: "outline",
  small: "small",
  textarea: "textarea",
  unstyled: "unstyled",
};

/** components/ThemeToggle/themeToggle.module.scss */
export const themeToggleStyles: ClassMap<"group" | "item"> = {
  group: "group",
  item: "item",
};

/** components/TimePicker/timePicker.module.scss */
export const timePickerStyles: ClassMap<
  "clearButton" | "clockIcon" | "popup" | "timePicker"
> = {
  clearButton: "clearButton",
  clockIcon: "clockIcon",
  popup: "popup",
  timePicker: "timePicker",
};

/** components/TimePicker/timePickerPanel.module.scss */
export const timePickerPanelStyles: ClassMap<
  | "disabled"
  | "selected"
  | "timeColumn"
  | "timeColumns"
  | "timePickerPanel"
  | "timeUnit"
> = {
  disabled: "disabled",
  selected: "selected",
  timeColumn: "timeColumn",
  timeColumns: "timeColumns",
  timePickerPanel: "timePickerPanel",
  timeUnit: "timeUnit",
};

/** components/Toast/toast.module.scss */
export const toastStyles: ClassMap<
  | "action"
  | "bottom-center"
  | "bottom-left"
  | "bottom-right"
  | "close"
  | "content"
  | "danger"
  | "description"
  | "icon"
  | "info"
  | "progress"
  | "success"
  | "title"
  | "toast"
  | "toastProgress"
  | "toastSlideIn"
  | "toastSlideOut"
  | "top-center"
  | "top-left"
  | "top-right"
  | "viewport"
  | "warning"
> = {
  action: "action",
  "bottom-center": "bottom-center",
  "bottom-left": "bottom-left",
  "bottom-right": "bottom-right",
  close: "close",
  content: "content",
  danger: "danger",
  description: "description",
  icon: "icon",
  info: "info",
  progress: "progress",
  success: "success",
  title: "title",
  toast: "toast",
  toastProgress: "toastProgress",
  toastSlideIn: "toastSlideIn",
  toastSlideOut: "toastSlideOut",
  "top-center": "top-center",
  "top-left": "top-left",
  "top-right": "top-right",
  viewport: "viewport",
  warning: "warning",
};

/** components/Tooltip/tooltip.module.scss */
export const tooltipStyles: ClassMap<
  | "animation-fade"
  | "animation-scale"
  | "arrow"
  | "danger"
  | "default"
  | "followCursor"
  | "glass"
  | "info"
  | "neutral"
  | "rippleRect"
  | "rounded"
  | "show"
  | "solid"
  | "square"
  | "subtle"
  | "success"
  | "thought"
  | "tooltip"
  | "tooltipArrow"
  | "tooltipTrigger"
  | "warning"
> = {
  "animation-fade": "animation-fade",
  "animation-scale": "animation-scale",
  arrow: "arrow",
  danger: "danger",
  default: "default",
  followCursor: "followCursor",
  glass: "glass",
  info: "info",
  neutral: "neutral",
  rippleRect: "rippleRect",
  rounded: "rounded",
  show: "show",
  solid: "solid",
  square: "square",
  subtle: "subtle",
  success: "success",
  thought: "thought",
  tooltip: "tooltip",
  tooltipArrow: "tooltipArrow",
  tooltipTrigger: "tooltipTrigger",
  warning: "warning",
};

/** components/Upload/upload.module.scss */
export const uploadStyles: ClassMap<
  | "actions"
  | "dragging"
  | "dropzone"
  | "error"
  | "info"
  | "item"
  | "label"
  | "list"
  | "preview"
  | "status"
  | "statusError"
  | "upload"
> = {
  actions: "actions",
  dragging: "dragging",
  dropzone: "dropzone",
  error: "error",
  info: "info",
  item: "item",
  label: "label",
  list: "list",
  preview: "preview",
  status: "status",
  statusError: "statusError",
  upload: "upload",
};

/** components/VirtualList/virtualList.module.scss */
export const virtualListStyles: ClassMap<
  | "clickable"
  | "loadingWrapper"
  | "virtualList"
  | "virtualListContent"
  | "virtualListItem"
> = {
  clickable: "clickable",
  loadingWrapper: "loadingWrapper",
  virtualList: "virtualList",
  virtualListContent: "virtualListContent",
  virtualListItem: "virtualListItem",
};
